/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'grachro' at '16/03/21 21:13' with Gradle 2.9
 *
 * @author grachro, @date 16/03/21 21:13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
